model:
  image_size: 128
  in_channels: 3
  base_channels: 128

diffusion:
  timesteps: 1100
  beta_start: 0.0001
  beta_end: 0.02

training:
  batch_size: 128
  epochs: 300
  learning_rate: 1e-4
  device: "cuda"
  data_dir: "./data"
  save_path: "./saves"
  num_workers: 6
  logs: "./logs/train-logs"

inference:
  model_path: "./saves/a.pth"
  device: "cuda"
  logs: "./logs/inference-logs"

api:
  host: "localhost"
  port: 8000
  reload: True

preprocessing:
  data_dir: "./data/plane"
  save_dir: "./data"
  